### ISSUE TITLE
read sftp password from netrc

### ISSUE THREAD

**Issue by drzraf** [lavv17/lftp#292]
lftp using **sftp** attempts to pass the password to the interactive prompt run by ssh.
But this only happens if the password is passed on the command line of lftp (-u flag), but not from the .netrc file.

Thus with a properly configured` .ssh/config` (hostname/alias/User), lftp won't connect even if the .netrc is properly configured (same `machine` name than used on the command line [and configured inside `.ssh/config`]).

**Comment by lavv17** [comment]
AFAIK lftp looks up a password in netrc file for any protocol. I'll try to
recheck this.

пн, 21 нояб. 2016, 1:39 Raphaël Droz <notifications@github.com>:

**Comment by barrycohen** [comment]
My guess would be you're doing something like this:

`lftp -c "open sftp://sftp.somesite.com ; ls"`

In this case it looks like lftp is trying to match `sftp://sftp.somesite.com` from `.netrc` rather than `sftp.somesite.com`.  You can work around this for now using:

`lftp -c "set cmd:default-protocol sftp ; open sftp.somesite.com ; ls"`

I tried putting `machine sftp://sftp.somesite.com` in .netrc but it doesn't seem to work.  I don't think this is how `.netrc` is supposed to be used anyway!

It would be nice if `NetRC::LookupHost()` stripped off protocol information.

**Comment by lavv17** [comment]
Specify the user name in the URL, then lftp will pick the password from
.netrc

пт, 25 нояб. 2016, 15:10 barrycohen <notifications@github.com>:

**Comment by barrycohen** [comment]
Ah, I see, thanks!  That's a better solution.

However, it still seems weird that `ftp.somesite.com` on its own will match an entry in `.netrc` but `ftp://ftp.somesite.com` will not.  Surely they amount to identical requests.

**Comment by lavv17** [comment]
See https://github.com/lavv17/lftp/blob/master/src/commands.cc#L1048
I have updated the documentation to reflect that the default user is used only when plain host name without a protocol is specified. In fact it was necessary for plain ftp compatibility.

**Comment by barrycohen** [comment]
Great, thanks very much.
